name: CI - Build and Test Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait and test endpoint from host
        run: |
          echo "Waiting for service to be ready..."
          # Use curl from the host machine, not from inside the container
          for i in {1..10}; do
            if curl -f http://localhost:5000; then
              echo "Success! Application is running."
              exit 0
            fi
            echo "Attempt $i failed, retrying in 5 seconds..."
            sleep 5
          done
          echo "All attempts failed"
          exit 1

      - name: Show container logs
        if: always()
        run: docker compose logs

      - name: Tear down containers
        if: always()
        run: docker compose down